# Generated by Django 3.2.7 on 2021-10-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spapp', '0004_alter_contact_us_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
