# Generated by Django 3.2.7 on 2021-10-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spapp', '0006_alter_contact_us_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=250, null=True)),
                ('cover_pic', models.FileField(upload_to='category/%y/%m/%d')),
                ('desc', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
