# Generated by Django 3.2.7 on 2021-10-06 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spapp', '0008_signup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name_plural': 'Sign Up'},
        ),
    ]
