# Generated by Django 3.2.7 on 2021-10-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spapp', '0009_alter_signup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
