# Generated by Django 3.2.7 on 2021-10-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spapp', '0010_alter_signup_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
