# Generated by Django 3.2.7 on 2021-10-08 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spapp', '0011_alter_signup_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cover_pic',
        ),
        migrations.RemoveField(
            model_name='category',
            name='desc',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_title', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('prod_price', models.IntegerField(blank=True, null=True)),
                ('prod_pic', models.FileField(upload_to='images/%y/%m/%d')),
                ('prod_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Spapp.category')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
    ]
