# Generated by Django 3.2.7 on 2021-10-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spapp', '0012_auto_20211008_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category of Product'},
        ),
        migrations.AddField(
            model_name='signup',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
